/// <summary>
/// 文件名称: OutputFile.cs
/// 
/// 功能描述: 定义生成的输出文件的数据结构，包含文件名、内容和元数据。
/// 
/// 创建日期: 2026-04-06
/// 修改日期: 2026-04-06
/// </summary>

using System;

namespace AbilityKit.CodeGen.Core
{
/// <summary>
/// 表示生成的输出文件。
/// </summary>
public readonly struct OutputFile
{
    /// <summary>生成文件的文件名</summary>
    public string FileName { get; }

    /// <summary>生成的源代码内容</summary>
    public string Content { get; }

    /// <summary>用于增量生成跟踪的提示名称</summary>
    public string HintName { get; }

    /// <summary>是否将此文件嵌入 PDB 以支持调试</summary>
    public bool EmbedInPdb { get; }

    /// <summary>是否将生成的文件添加到项目</summary>
    public bool AddToProject { get; }

    /// <summary>文件所在的子目录路径</summary>
    public string SubDirectory { get; }

    private OutputFile(
        string fileName,
        string content,
        string hintName,
        bool embedInPdb,
        bool addToProject,
        string subDirectory)
    {
        FileName = fileName ?? throw new ArgumentNullException(nameof(fileName));
        Content = content ?? string.Empty;
        HintName = hintName ?? fileName;
        EmbedInPdb = embedInPdb;
        AddToProject = addToProject;
        SubDirectory = subDirectory ?? string.Empty;
    }

    /// <summary>创建输出文件实例</summary>
    public static OutputFile Create(
        string fileName,
        string content,
        string hintName = null,
        bool embedInPdb = true,
        bool addToProject = false,
        string subDirectory = null)
    {
        return new OutputFile(fileName, content, hintName, embedInPdb, addToProject, subDirectory);
    }

    /// <summary>创建带目录路径的输出文件</summary>
    public static OutputFile CreateWithDirectory(
        string directory,
        string fileName,
        string content,
        string hintName = null)
    {
        var fullPath = string.IsNullOrEmpty(directory)
            ? fileName
            : $"{directory}/{fileName}";

        return Create(fullPath, content, hintName);
    }

    /// <summary>获取包含子目录的完整文件路径</summary>
    public string GetFullPath()
    {
        return string.IsNullOrEmpty(SubDirectory)
            ? FileName
            : $"{SubDirectory}/{FileName}";
    }

    /// <summary>获取自动生成文件的标头注释</summary>
    public static string GetAutoGeneratedHeader()
    {
        return "// <auto-generated/>\n#nullable enable\n";
    }

    /// <summary>获取添加了自动生成标头的内容</summary>
    public string GetContentWithHeader()
    {
        return GetAutoGeneratedHeader() + Content;
    }
}
}