// <auto-generated>
// Generated by GameplayTagManagerWindow
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AbilityKit.Ability.Share.Common.TagSystem
{
    public static class GameplayTagLib
    {
        public static class Names
        {
            public const string A_B_C = "A.B.C";
        }

        public static class Tags
        {
            public static readonly GameplayTag A_B_C = GameplayTags.Tag(Names.A_B_C);
        }

        private static bool s_registered;

        public static void RegisterAll()
        {
            if (s_registered) return;
            s_registered = true;
            GameplayTags.Tag(Names.A_B_C);
        }

        public static IReadOnlyList<string> AllNames { get; } = new[]
        {
            Names.A_B_C,
        };

        public static IReadOnlyList<GameplayTag> AllTags { get; } = new[]
        {
            Tags.A_B_C,
        };
    }
}
