
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace cfg
{
public partial class Tables
{
    public DTBuff DTBuff {get; }
    public demo.Tbitem Tbitem {get; }


      public Tables(System.Func<string, JArray> loader)
    {
        DTBuff = new DTBuff(loader("dtbuff"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        ResolveRef();
    }
    
     private void ResolveRef()
    {
        DTBuff.ResolveRef(this);
        Tbitem.ResolveRef(this);
    }
}

}

