// <auto-generated>
// 由 GameplayTagGenerator 自动生成
// 不要手动修改此文件
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AbilityKit.GameplayTags
{
    /// <summary>
    /// 预定义的常用标签库，自动注册所有预定义标签。
    /// 使用 GameplayTagLib.Tag(...) 获取标签。
    /// </summary>
    public static class GameplayTagsLib
    {
        private static bool s_registered;

        /// <summary>
        /// 注册所有预定义标签到 GameplayTagManager
        /// </summary>
        public static void RegisterAll()
        {
            if (s_registered) return;
            s_registered = true;

            // 在此注册所有预定义标签
            // 例如: Tag("Status.Stun");
        }

        /// <summary>
        /// 获取所有预定义标签名称
        /// </summary>
        public static IReadOnlyList<string> AllNames { get; } = Array.Empty<string>();

        /// <summary>
        /// 获取所有预定义标签
        /// </summary>
        public static IReadOnlyList<GameplayTag> AllTags { get; } = Array.Empty<GameplayTag>();

        /// <summary>
        /// 标签访问器
        /// </summary>
        public static GameplayTag Tag(string name)
        {
            return GameplayTags.Tag(name);
        }
    }
}
