
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class DRBuff : Luban.BeanBase
{
    public DRBuff(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        DurationMs = _buf.ReadInt();
        OngoingEffectId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); OnAddEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnAddEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnRemoveEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnRemoveEffects.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnIntervalEffects = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); OnIntervalEffects.Add(_e0);}}
        IntervalMs = _buf.ReadInt();
        StackingPolicy = _buf.ReadInt();
        RefreshPolicy = _buf.ReadInt();
        MaxStacks = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); TriggerIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TriggerIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Tags.Add(_e0);}}
    }

    public static DRBuff DeserializeDRBuff(ByteBuf _buf)
    {
        return new DRBuff(_buf);
    }

    /// <summary>
    /// 属性编号
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 持续毫秒
    /// </summary>
    public readonly int DurationMs;
    /// <summary>
    /// 持续生效效果id
    /// </summary>
    public readonly int OngoingEffectId;
    /// <summary>
    /// 添加时效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnAddEffects;
    /// <summary>
    /// 移除时效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnRemoveEffects;
    /// <summary>
    /// 间隔触发效果
    /// </summary>
    public readonly System.Collections.Generic.List<int> OnIntervalEffects;
    /// <summary>
    /// 间隔毫秒
    /// </summary>
    public readonly int IntervalMs;
    /// <summary>
    /// 叠加方式
    /// </summary>
    public readonly int StackingPolicy;
    /// <summary>
    /// 刷新方式
    /// </summary>
    public readonly int RefreshPolicy;
    /// <summary>
    /// 最大层数
    /// </summary>
    public readonly int MaxStacks;
    /// <summary>
    /// 监听效果列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> TriggerIds;
    /// <summary>
    /// 标签列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> Tags;
   
    public const int __ID__ = 2024592897;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DurationMs:" + DurationMs + ","
        + "OngoingEffectId:" + OngoingEffectId + ","
        + "OnAddEffects:" + Luban.StringUtil.CollectionToString(OnAddEffects) + ","
        + "OnRemoveEffects:" + Luban.StringUtil.CollectionToString(OnRemoveEffects) + ","
        + "OnIntervalEffects:" + Luban.StringUtil.CollectionToString(OnIntervalEffects) + ","
        + "IntervalMs:" + IntervalMs + ","
        + "StackingPolicy:" + StackingPolicy + ","
        + "RefreshPolicy:" + RefreshPolicy + ","
        + "MaxStacks:" + MaxStacks + ","
        + "TriggerIds:" + Luban.StringUtil.CollectionToString(TriggerIds) + ","
        + "Tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "}";
    }
}
}

