using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AbilityKit.Demo.Moba.CodeGen
{
    [Generator]
    public sealed class MobaBTreeNodeManifestGenerator : ISourceGenerator
    {
        private const string NodeBaseMetadataName = "BTCore.Runtime.BTNode";
        private const string ManifestMetadataName =
            "AbilityKit.Demo.Moba.Services.Behavior.BTree.MobaGeneratedBTreeNodeManifest";

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new BTreeNodeSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (!(context.SyntaxContextReceiver is BTreeNodeSyntaxReceiver receiver)) return;

            var nodeBaseType = context.Compilation.GetTypeByMetadataName(NodeBaseMetadataName);
            var manifestType = context.Compilation.GetTypeByMetadataName(ManifestMetadataName);
            if (nodeBaseType == null || manifestType == null ||
                !manifestType.Locations.Any(location => location.IsInSource)) return;

            var nodes = new List<NodeMapping>();
            var seenTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var type in receiver.Types)
            {
                if (!seenTypes.Add(type) ||
                    !MobaBTreeNodeContract.IsCandidate(type, nodeBaseType))
                {
                    continue;
                }

                if (!MobaBTreeNodeContract.TryValidate(type, out _))
                {
                    continue;
                }

                nodes.Add(new NodeMapping(type));
            }

            var duplicateTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
            foreach (var group in nodes.GroupBy(node => node.NodeName, StringComparer.Ordinal))
            {
                var entries = group.OrderBy(node => node.QualifiedTypeName, StringComparer.Ordinal).ToArray();
                if (entries.Length <= 1) continue;

                foreach (var entry in entries) duplicateTypes.Add(entry.NodeType);
            }

            nodes.RemoveAll(node => duplicateTypes.Contains(node.NodeType));
            nodes.Sort((left, right) => string.CompareOrdinal(left.NodeName, right.NodeName));
            context.AddSource("MobaGeneratedBTreeNodeManifest.g.cs", GenerateSource(nodes));
        }

        private static string GenerateSource(IReadOnlyList<NodeMapping> nodes)
        {
            var source = new StringBuilder();
            source.AppendLine("// <auto-generated/>");
            source.AppendLine("namespace AbilityKit.Demo.Moba.Services.Behavior.BTree");
            source.AppendLine("{");
            source.AppendLine("    internal static partial class MobaGeneratedBTreeNodeManifest");
            source.AppendLine("    {");
            source.AppendLine("        static partial void AddGenerated(global::System.Collections.Generic.Dictionary<string, global::System.Type> nodeTypes)");
            source.AppendLine("        {");
            foreach (var node in nodes)
            {
                source.Append("            nodeTypes.Add(")
                    .Append(Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(node.NodeName, true))
                    .Append(", typeof(").Append(node.QualifiedTypeName).AppendLine("));");
            }

            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            return source.ToString();
        }

        private sealed class NodeMapping
        {
            public NodeMapping(INamedTypeSymbol nodeType)
            {
                NodeType = nodeType;
                NodeName = nodeType.Name;
                QualifiedTypeName = nodeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }

            public INamedTypeSymbol NodeType { get; }
            public string NodeName { get; }
            public string QualifiedTypeName { get; }
        }
    }

    internal sealed class BTreeNodeSyntaxReceiver : ISyntaxContextReceiver
    {
        public List<INamedTypeSymbol> Types { get; } = new List<INamedTypeSymbol>();

        public void OnVisitSyntaxNode(GeneratorSyntaxContext context)
        {
            if (context.Node is ClassDeclarationSyntax declaration &&
                context.SemanticModel.GetDeclaredSymbol(declaration) is INamedTypeSymbol type)
            {
                Types.Add(type);
            }
        }
    }
}
