/// <summary>
/// 文件名称: GeneratorOutputAttribute.cs
/// 
/// 功能描述: 定义生成代码输出配置的的特性，用于指定生成文件的行为。
/// 
/// 创建日期: 2026-04-06
/// 修改日期: 2026-04-06
/// </summary>

using System;

namespace AbilityKit.CodeGen.Attributes
{
/// <summary>
/// 指定生成代码的输出配置。
/// </summary>
[AttributeUsage(
    AttributeTargets.Class |
    AttributeTargets.Struct |
    AttributeTargets.Method,
    AllowMultiple = false,
    Inherited = false)]
public sealed class GeneratorOutputAttribute : Attribute
{
    /// <summary>生成文件的文件名</summary>
    public string FileName { get; set; }

    /// <summary>生成文件所在的子目录</summary>
    public string SubDirectory { get; set; }

    /// <summary>是否将生成文件嵌入 PDB</summary>
    public bool EmbedInPdb { get; set; } = true;

    /// <summary>是否抑制自动生成文件的标头注释</summary>
    public bool SuppressAutoGeneratedComment { get; set; }

    public GeneratorOutputAttribute() { }

    public GeneratorOutputAttribute(string fileName)
    {
        FileName = fileName;
    }
}
}